language: python

python:
    - "3.4"

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install python-numpy
    - node -v
    - npm install npm
    - npm -v
    - npm install lodash

script:
    - cd javascript
    - make test
    - cd -
    - cd python
    - make test
