language: python

python:
    - "3.4"

install:
    - sudo apt-get install nodejs
    - sudo apt-get install node-lodash
    - sudo apt-get install python-numpy

script:
    - cd javascript
    - make test
    - cd -
    - cd python
    - make test
