language: node_js

node_js:
    - "0.12"

before_install:
    - sudo apt-get update

install:
    - sugo apt-get install python3.4
    - sudo apt-get install python-numpy
    - npm install npm      -g
    - npm install mocha    -g
    - npm install istanbul -g
    - npm install lodash

script:
    - cd javascript
    - make test
    - cd -
    - cd python
    - make test
