language: python

python:
    - "3.4"

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install python-numpy
    - npm install npm      -g
    - npm install mocha    -g
    - npm install istanbul -g
    - npm install lodash
    - pip -V

script:
    - cd javascript
    - make test
    - cd -
    - cd python
    - make test
