language: python

python:
    - "3.4"

install:
    - sudo apt-get install nodejs
    - sudo apt-get install npm
    - sudo apt-get install python-numpy
    - sudo npm     install lodash

script:
    - cd javascript
    - make test
    - cd -
    - cd python
    - make test
