language: python

python:
    - "3.4"

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install python-numpy
    - sudo apt-get install nodejs
    - npm install npm
    - npm install lodash
    - npm install mocha

script:
    - cd javascript
    - make test
    - cd -
    - cd python
    - make test
