language: python

python:
    - "3.4"

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install python-numpy
    - npm install

script:
    - cd javascript
    - make test
    - cd -
    - cd python
    - make test
