all:

test:
	xmllint --noout                            Bookstore1.xml
	xmllint --noout --valid                    Bookstore1.dtd.xml
	xmllint --noout --valid                    Bookstore2.dtd.xml
	xmllint --noout -schema Bookstore3.xsd.xml Bookstore3.xml
